### PR TITLE
refactored harbor-rpm-ansible

### PR DESCRIPTION
**Pull request by patsevanton**

### CODE REVIEW

**Comment by patsevanton** [comment]
log install harbor-rpm-ansible

https://gist.github.com/patsevanton/b7568a5e0d5ca3c3f377fe1f44ab68e6

**Comment by patsevanton** [comment]
image

**Comment by patsevanton** [comment]
image


i don`t found "http://clair-adapter:8080" in configuration

**Comment by MrMEEE** [comment]
Hi

Thanks for the PR.. but I don't wanna change from SCL to the PostgreSQL repos, as for the RHEL users, the SCL repos has support.. can you make a PR without the repo changes??

**Comment by MrMEEE** [comment]
In regards to the scanner.. I haven't tested the new modular scanner configuration yet.. but you should be able to delete that clair-adapter scanner and add a new one with the local clair daemon..

**Comment by patsevanton** [comment]
I don`t know how use SCL PostgreSQL.
Use only Official PostgreSQL.

**Comment by MrMEEE** [comment]
Just leave it out? the way I implemented it in the first case?

**Comment by patsevanton** [comment]
I did not understand SCL PostgreSQL. Sorry.

**Pull request closed without merging**
